
// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `default`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `server=116.62.208.130;database=Travel; User ID=sa;Password=yannis_123@live.com`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace Travel.Domain.Models
{
    /// <summary>
    /// A class which represents the Category table.
    /// </summary>
	[Table("Category")]
	public partial class Category
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string CategoryName { get; set; }
		public virtual int ParentId { get; set; }
		public virtual int Sort { get; set; }
		public virtual string CreateBy { get; set; }
		public virtual int ModifyBy { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual DateTime ModifyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Project table.
    /// </summary>
	[Table("Project")]
	public partial class Project
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual string Name { get; set; }
		public virtual int CategoryId { get; set; }
		public virtual string Describe { get; set; }
		public virtual string Content { get; set; }
		public virtual decimal Price { get; set; }
		public virtual string Picture { get; set; }
		public virtual string StartDate { get; set; }
		public virtual int State { get; set; }
		public virtual bool IsRecommend { get; set; }
		public virtual int CreateBy { get; set; }
		public virtual int ModifyBy { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual DateTime ModifyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Article table.
    /// </summary>
	[Table("Article")]
	public partial class Article
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int ArticleType { get; set; }
		public virtual string Title { get; set; }
		public virtual string Describe { get; set; }
		public virtual string Picture { get; set; }
		public virtual string Content { get; set; }
		public virtual int ViewCount { get; set; }
		public virtual int State { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual DateTime ModifyTime { get; set; }
		public virtual int CreateBy { get; set; }
		public virtual int ModifyBy { get; set; }
	}

    /// <summary>
    /// A class which represents the Manager  table.
    /// </summary>
	[Table("Manager ")]
	public partial class Manager
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string UserName { get; set; }
		public virtual string Password { get; set; }
		public virtual string Mobile { get; set; }
		public virtual int State { get; set; }
		public virtual int LoginCount { get; set; }
		public virtual DateTime LastloginTime { get; set; }
		public virtual int CreateBy { get; set; }
		public virtual int ModifyBy { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual DateTime ModifyTime { get; set; }
	}

    /// <summary>
    /// A class which represents the Role table.
    /// </summary>
	[Table("Role")]
	public partial class Role
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string RoleName { get; set; }
		public virtual int RoleType { get; set; }
		public virtual bool IsDefault { get; set; }
		public virtual int State { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual string CreateBy { get; set; }
		public virtual DateTime ModifyTime { get; set; }
		public virtual string ModifyBy { get; set; }
	}

    /// <summary>
    /// A class which represents the Advertisement table.
    /// </summary>
	[Table("Advertisement")]
	public partial class Advertisement
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int AdType { get; set; }
		public virtual string AdName { get; set; }
		public virtual string AdLink { get; set; }
		public virtual string AdPicture { get; set; }
		public virtual int Sort { get; set; }
		public virtual int State { get; set; }
		public virtual int CreateBy { get; set; }
		public virtual int ModifyBy { get; set; }
		public virtual DateTime CreateTime { get; set; }
		public virtual DateTime ModifyTime { get; set; }
	}

}
